# PANDAS

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame({"Name" : ["Ishan", "Airan" , "python"] , "age" : [20,20,43]})

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [8]:
df.isnull().sum()

Name    0
age     0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [17]:
df = pd.read_csv("Salary_Dataset_DataScienceLovers.csv")

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22770 entries, 0 to 22769
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rating             22770 non-null  float64
 1   Company Name       22769 non-null  str
 2   Job Title          22770 non-null  str
 3   Salary             22770 non-null  int64
 4   Salaries Reported  22770 non-null  int64
 5   Location           22770 non-null  str
 6   Employment Status  22770 non-null  str
 7   Job Roles          22770 non-null  str
dtypes: float64(1), int64(2), str(5)
memory usage: 1.4 MB

In [40]:
df.describe()

             Rating        Salary  Salaries Reported
count  22770.000000  2.277000e+04       22770.000000
mean       3.918213  6.953872e+05           1.855775
std        0.519675  8.843990e+05           6.823668
min        1.000000  2.112000e+03           1.000000
25%        3.700000  3.000000e+05           1.000000
50%        3.900000  5.000000e+05           1.000000
75%        4.200000  9.000000e+05           1.000000
max        5.000000  9.000000e+07         361.000000

In [42]:
df.isnull().sum()

Rating               0
Company Name         1
Job Title            0
Salary               0
Salaries Reported    0
Location             0
Employment Status    0
Job Roles            0
dtype: int64

In [27]:
df.head(15)

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
0,3.8,Sasken,Android Developer,400000,3,Bangalore,Full Time,Android
1,4.5,Advanced Millennium Technologies,Android Developer,400000,3,Bangalore,Full Time,Android
2,4.0,Unacademy,Android Developer,1000000,3,Bangalore,Full Time,Android
3,3.8,SnapBizz Cloudtech,Android Developer,300000,3,Bangalore,Full Time,Android
4,4.4,Appoids Tech Solutions,Android Developer,600000,3,Bangalore,Full Time,Android
5,4.2,Freelancer,Android Developer,100000,3,Bangalore,Full Time,Android
6,3.7,SQUARE N CUBE,Android Developer,192000,3,Bangalore,Full Time,Android
7,3.1,Samsung R&D Institute India - Bangalore,Android Developer,400000,3,Bangalore,Full Time,Android
8,3.7,DXMinds Technologies,Android Developer,300000,3,Bangalore,Full Time,Android
9,3.6,Endeavour Software Technologies,Android Developer,600000,3,Bangalore,Full Time,Android
10,3.6,Craft Silicon,Android Developer,300000,3,Bangalore,Full Time,Android
11,3.9,Baronford & Associates,Android Developer,240000,2,Bangalore,Full Time,Android
12,3.7,Wibmo,Android Developer,900000,2,Bangalore,Full Time,Android
13,4.8,Retail Pulse,Android Developer - Intern,24000,2,Bangalore,Intern,Android
14,3.9,Bookmyshow,Android Developer,600000,2,Bangalore,Full Time,Android

In [34]:
df["Company Name"].nunique()

11260

In [39]:
df["Company Name"].isnull().sum()

np.int64(1)

In [52]:
df["Company Name"].describe()

count                         22769
unique                        11260
top       Tata Consultancy Services
freq                            271
Name: Company Name, dtype: object

In [59]:
df[["Company Name", "Salary"]].sort_values(by="Salary", ascending=False).head(10)

                 Company Name    Salary
18635       Thapar University  90000000
9260        OASYS Cybernetics  10000000
4471               Concentrix  10000000
7121           Koru UX Design  10000000
5819           Nityo Infotech   9900000
16062                  Amazon   9850000
18654            Digital Raju   9800000
16619         FFF Enterprises   9800000
15568  Gaana Lyrics Point.com   9700000
10832    GGH Heavy Industries   9600000

In [68]:
df.isna().sum()

Rating               0
Company Name         1
Job Title            0
Salary               0
Salaries Reported    0
Location             0
Employment Status    0
Job Roles            0
dtype: int64

In [69]:
df[df["Company Name"].isna()]

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
13760,4.0,NaN,Software Development Engineer,1188000,1,Bangalore,Full Time,SDE

In [70]:
df = df.dropna(subset=["Company Name"])

In [72]:
df[df["Company Name"].isna()]

Empty DataFrame
Columns: [Rating, Company Name, Job Title, Salary, Salaries Reported, Location, Employment Status, Job Roles]
Index: []

### Since there was only one null value , we simply dropped it , if it would have been around <60% we could have managed it through .fillna() else if it's >80% we drop the whole column