# **Machine Learning Model steps**


1. Import all libraries like numpy,pandas,tensor/keras, sklearn
2. Import Data using pandas, pd.read_csv
3. EDA or prepocessing like encoding, transforming
4. Data Cleaning
5. Make target variables x and y then divide data into two parts:- training , testing using train_test_split in ratio 8:2 o 7:3
6. Import ML model
7. Fit training data into model using model.fit()
8. Predict using the data using .predict function:- model.predict(data)
9. Check the evaluation:- R2 score,F1 score, accuracy
10. Convert model into pkl file
11. Making the GUI.
12. Pkl file adjusts into GUI code.

In [9]:
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import pickle
import seaborn as sns

# *Importing and Cleaning the Data*

In [10]:
df=sns.load_dataset('iris')
df.head()
print(df.isnull().sum())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
df.dropna(inplace=True)
print(df.isnull().sum())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [12]:
df = df[df['species'] != 'versicolor']
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [13]:
df['species'] = df['species'].map({
    'setosa': 0,
    'virginica': 1
})
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [14]:
x=df[['sepal_length','sepal_width','petal_length','petal_width']]
y=df[['species']]
print(len(x))
print(len(y))

100
100

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(len(x_train))
print(len(x_test))

80
20

# **Importing the ML Model and predicting the salary**

In [16]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

c:\Users\PRAKHAR\OneDrive\Desktop\Day_8\.venv\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [17]:
y_pred=pd.DataFrame(y_pred)
y_pred.head()

   0
0  1
1  1
2  1
3  0
4  0

In [18]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

# **Saving the model using pickle**

In [19]:
with open("flower_model.pkl", "wb") as file:
    pickle.dump(lr, file)

print("Model Saved Successfully!")

Model Saved Successfully!

# Loading the **model**

In [20]:
with open('flower_model.pkl',"rb")as f:
  model=pickle.load(f)

y=bx+c, b= biasness, c=coefficient, :- linear regression
Logistic Regression:- uses categorical data , gives output in binary format,uses sigmoid function if valye comes greater than 0.5 then 1 else 0 as a output